### ISSUE TITLE
Sending transactions and re-initializing the wallet results in untracked utxos

### ISSUE THREAD

**Issue by dashameter** [dashevo/wallet-lib#146]
## Current Behavior

Sending txs works a few times until all receiving addresses are depleted with the change having accumulated in change addresses. The problem seems to be related but not exclusive to the wallet loosing track of `utxos` when re-initializing with the same mnemonic.

Then I get errors of the like:

```
Insufficient funds to cover output
```
```
CreateTransactionError: Error: utxosList must contain at least 1 utxo
```

```
3 INVALID_ARGUMENT: invalid transaction: Missing inputs. Code:-25
```

```
account.getConfirmedBalance() :>>  8731592178
account.getUnconfirmedBalance() :>>  0
Something went wrong: { Error: 3 INVALID_ARGUMENT: invalid transaction: 66: min relay fee not met. Code:-26
```

**Comment by Alex-Werner** [comment]
Thank you @dashameter for the reporting this bug ! 
https://github.com/dashevo/wallet-lib/pull/151 and https://github.com/dashevo/wallet-lib/pull/149 
fixes it and has been merged into https://github.com/dashevo/wallet-lib/pull/153 released as 7.13.3. 
Please re-open this issue if you still encounter this bug :)
We also added additional test to cover one part of this, and a second one will ensure we cover depleted internal addresses (>20).
