### ISSUE TITLE
account.sign(transaction) throws error 'Require one or multiple privateKeys to sign'

### ISSUE THREAD

**Issue by dashameter** [dashevo/wallet-lib#160]
## Expected Behavior
Will find the privateKey from keychain for you and sign a transaction e.g. when the tx looses its signatures by adding OP_RETURN data using `transaction.addData('correct horse battery staple')` . via https://dashevo.github.io/wallet-lib/#/account/sign

## Current Behavior
throws error:
```
Something went wrong: Error: Require one or multiple privateKeys to sign
    at KeyChain.sign (node_modules/@dashevo/wallet-lib/src/types/KeyChain/methods/sign.js:13:27)
    at Account.sign (node_modules/@dashevo/wallet-lib/src/types/Account/methods/sign.js:8:24)
    at sendFunds (sendFunds.js:21:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Steps to Reproduce (for bugs)
Run example code:
https://gist.github.com/dashameter/fce17bad0d97ab644d0cff0acb98cbcc

**Comment by dashameter** [comment]
Another context where `account.sign()` throws the same error instead of looking up the private keys for signing:


```
const UTXO = DAPIclient.getUTXO(address)
const transaction = account.createTransaction({
        recipient,
        satoshis,
        utxos: UTXO.items,
})

const signedTx = account.sign(transaction); // Will find the privateKey from keychain for you.

```

**Comment by Alex-Werner** [comment]
Closing this issue as #188 should have fixed this already. 

Do not hesitate to re-open if you find a similar issue. 

Thanks,
