### ISSUE TITLE
add startBlockHeight parameter to reduce init time for testnet development

### ISSUE THREAD

**Issue by dashameter** [dashevo/wallet-lib#216]
Add a parameter ```getWalletAccount( { startBlockHeight: 50000 } )``` to speed up development and testing on testnet by reduce the wallet load time.

Discussion:

https://discord.com/channels/670271785974890526/670599939528851476/795503442176114708

https://discord.com/channels/670271785974890526/670599939528851476/795624579980066856

**Comment by antouhou** [comment]
@dashameter What do you think if we add something like `{ debugOptions: { skipSyncronizationBeforeHeight: 50000 } }`? This way it would be clear that this is something that's not intended for production use

**Comment by Alex-Werner** [comment]
Closing this as #217 allows to pass `skipSynchronizationBeforeHeight` options. 

Thank you !
