### ISSUE TITLE
account.getUTXOS() returns empty array (forgets UTXOS) upon client init using mn-bootstrap local config

### ISSUE THREAD

**Issue by dashameter** [dashevo/wallet-lib#231]
Using `mn-bootstrap` in local setup:

`account.getUTXOS()` loses all existing UTXOS and returns an empty array upon client re-init (refreshing the browser page) when unless the utxo has been directly mined using the `mn wallet:mint` command. 

`await client.getWalletAccount()` will not show any, txs or balance that already existent prior to calling the function, the receiving address shows `used: false` until a new tx is sent while the client is connected.

This makes feature development difficult / less portable to testnet.

https://discord.com/channels/670271785974890526/670599939528851476/802438229537587200

https://discord.com/channels/670271785974890526/670599939528851476/809021255906099250

**Comment by dashameter** [comment]
@Alex-Werner are we tracking this bug to be fixed in one of the upcoming releases or shall we bounty it out to the incubator?

**Comment by Alex-Werner** [comment]
It is being tracked, yes, we are aware of that, and we do have separate task for this. 
One specific to this subject and the other on why getUTXOS() returns empty array (maturity is set to 100 blocks)

**Comment by SamKirby22** [comment]
Discussed in Triage - P1, Maverick to discuss with Alex.

**Comment by dash-maverick** [comment]
Most probably will be delivered right after v21.

**Comment by dash-maverick** [comment]
should be fixed - please retest

**Comment by dashameter** [comment]
passed retest

**Comment by SamKirby22** [comment]
Triage sheet updated. Thanks.
