### ISSUE TITLE
chain transactions to avoid mempool conflicts

### ISSUE THREAD

**Issue by dashameter** [dashevo/wallet-lib#232]
If the wallet has its entire balance in 1 utxo, then e.g. identity creation will block any other L1 interactions with mempool conflict.

wallet-lib should keep track of that spent utxo that is now in mempool and chain future L1 transactions.

https://discord.com/channels/670271785974890526/670540408593448980/809996041411625020

https://discord.com/channels/670271785974890526/670540408593448980/810207088286367764

**Comment by Alex-Werner** [comment]
cc:@dalibran  This will be an issue to Developer Experience as they might not understand reason of it failing. I would suggest us to have this on our backlog and assign it a decent priority (I really think we should have this working for mainnet).

**Comment by dash-maverick** [comment]
Just as an update - this is being progressed on DCG side and is supposed to be completed soon. The fix should also solve problems described in

- https://github.com/dashevo/wallet-lib/issues/178
- https://github.com/dashevo/wallet-lib/issues/201

**Comment by dash-maverick** [comment]
@dashameter @SamKirby22 should be solved from now - please double check

**Comment by dashameter** [comment]
passed retest
