### ISSUE TITLE
Register identity throws TypeError: n.isCoinbase is not a function

### ISSUE THREAD

**Issue by ghost** [dashevo/wallet-lib#236]
When creating an identity (on a fresh mnemonic) in Browser/Chrome Wallet with dash-js v18.1 it throws this error:
```
TypeError: n.isCoinbase is not a function
```
Used mnemonic: spy turtle misery velvet fine ball panda auction repeat tent ghost above
Account balance is 39 tDash
![image](https://user-images.githubusercontent.com/60034953/111597317-542a4080-87ce-11eb-94c5-7d9eb0ad9a2f.png)

**Comment by shumkov** [comment]
@readme55 Could you provide a not minified stack trace, please?

**Comment by readme55** [comment]
@shumkov
this is the error with un-minified dash-js v19:
![image](https://user-images.githubusercontent.com/60034953/113478078-cbc2c580-9486-11eb-9139-b0f0a971bb6a.png)

**Comment by antouhou** [comment]
Should be fixed by #246

**Comment by dashameter** [comment]
passed retest

@SamKirby22 can be closed

**Comment by SamKirby22** [comment]
Thanks @dashameter - closed
