### ISSUE TITLE
doc: getTransactionHistory returns empty array, should be getTransactions

### ISSUE THREAD

**Issue by dashameter** [dashevo/wallet-lib#256]
https://dashevo.github.io/wallet-lib/#/account/getTransactionHistory

`getTransactionHistory` doesn't exist on type account, if account is cast to `any` it returns an empty array.

`getTransactions` exist on the type account and returns the transactions, but is not listed in the documentation.

**Comment by SamKirby22** [comment]
Discussed in Triage - marged and ready for retest in v21

**Comment by dashameter** [comment]
`getTransactionHistory` is working now, amazing :+1: the type on `Account` and the documentation for it appear to still be missing

**Comment by dash-maverick** [comment]
docs will be updated soon, thanks for summarizing that

**Comment by dashameter** [comment]
passed retest, fixed on v.22
